spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  cache:
    cache-names:
    - cats
    - dogs
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
server:
  port: 8082